# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: af66dbbf3b9689b0210de997dd930ff88eaea770693e3b0054fe2d47c9d3bf6751995824a4bfa1a808cc852f9fc91ff0adcc51f3d5bf885b9f372a3b7daa9ceb

test:
  secret_key_base: 4f5e7d6d96d63cc8476cfc06023def9b386a1916c0cf93137438236b82e2c15cf98b2e92ee433722dd705c34464218754aad708f42f6af453ef52204a6c77ff7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
